/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as VoorWieRouteImport } from './routes/voor-wie'
import { Route as VoorWieSegmentRouteImport } from './routes/voor-wie.$segment'
import { Route as AssortimentCategoryRouteImport } from './routes/assortiment.$category'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/assortiment',
  path: '/assortiment',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorWieRoute = VoorWieRouteImport.update({
  id: '/voor-wie',
  path: '/voor-wie',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorWieSegmentRoute = VoorWieSegmentRouteImport.update({
  id: '/voor-wie/$segment',
  path: '/voor-wie/$segment',
  getParentRoute: () => rootRouteImport,
} as any)
const AssortimentCategoryRoute = AssortimentCategoryRouteImport.update({
  id: '/assortiment/$category',
  path: '/assortiment/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/ons-verhaal',
  path: '/ons-verhaal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ons-verhaal': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/assortiment': typeof ServicesRoute
  '/assortiment/$category': typeof AssortimentCategoryRoute
  '/voor-wie': typeof VoorWieRoute
  '/voor-wie/$segment': typeof VoorWieSegmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ons-verhaal': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/assortiment': typeof ServicesRoute
  '/assortiment/$category': typeof AssortimentCategoryRoute
  '/voor-wie': typeof VoorWieRoute
  '/voor-wie/$segment': typeof VoorWieSegmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ons-verhaal': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/assortiment': typeof ServicesRoute
  '/assortiment/$category': typeof AssortimentCategoryRoute
  '/voor-wie': typeof VoorWieRoute
  '/voor-wie/$segment': typeof VoorWieSegmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ons-verhaal' | '/contact' | '/assortiment' | '/assortiment/$category' | '/voor-wie' | '/voor-wie/$segment'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ons-verhaal' | '/contact' | '/assortiment' | '/assortiment/$category' | '/voor-wie' | '/voor-wie/$segment'
  id: '__root__' | '/' | '/ons-verhaal' | '/contact' | '/assortiment' | '/assortiment/$category' | '/voor-wie' | '/voor-wie/$segment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  AssortimentCategoryRoute: typeof AssortimentCategoryRoute
  VoorWieRoute: typeof VoorWieRoute
  VoorWieSegmentRoute: typeof VoorWieSegmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/assortiment': {
      id: '/assortiment'
      path: '/assortiment'
      fullPath: '/assortiment'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assortiment/$category': {
      id: '/assortiment/$category'
      path: '/assortiment/$category'
      fullPath: '/assortiment/$category'
      preLoaderRoute: typeof AssortimentCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voor-wie': {
      id: '/voor-wie'
      path: '/voor-wie'
      fullPath: '/voor-wie'
      preLoaderRoute: typeof VoorWieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voor-wie/$segment': {
      id: '/voor-wie/$segment'
      path: '/voor-wie/$segment'
      fullPath: '/voor-wie/$segment'
      preLoaderRoute: typeof VoorWieSegmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ons-verhaal': {
      id: '/ons-verhaal'
      path: '/ons-verhaal'
      fullPath: '/ons-verhaal'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  AssortimentCategoryRoute: AssortimentCategoryRoute,
  VoorWieRoute: VoorWieRoute,
  VoorWieSegmentRoute: VoorWieSegmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
